name: Release

on:
  push:
    tags:
      - v*

env:
  GO_VERSION: '1.25'
  CGO_ENABLED: 0

jobs:

  push: 
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
    timeout-minutes: 20
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
      timeout-minutes: 2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      timeout-minutes: 2

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host
      timeout-minutes: 2

    # This step is needed to expose ACTIONS_CACHE_URL & ACTIONS_RUNTIME_TOKEN to
    # docker buildx so that it can cache build steps. 
    - name: Expose GitHub Runtime env vars
      uses: crazy-max/ghaction-github-runtime@v3
      timeout-minutes: 2

    - name: Build and push docker image
      run: |
        export REGISTRY=ghcr.io
        export IMAGE=$REGISTRY/kubernetes-sigs/external-dns
        make push-multi-arch-image
      timeout-minutes: 20
